language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
before_script:
  - bundle install
  - sudo apt-get install build-essential
  - git clone --branch=go1.4.1 --depth=1 https://github.com/golang/go.git ~/go
  - pushd ~/go/src && ./make.bash && popd
  - mkdir -p ~/src/github.com/DavidHuie
  - ln -s `pwd` ~/src/github.com/DavidHuie/quartz
env:
  - GOROOT=~/go GOPATH=~/ PATH=$GOROOT/bin:$GOPATH/bin:$PATH
script:
  - bundle exec rake
  - go test ./go/quartz