language: ruby
rvm:
  - 2.5.1
before_script:
  - sudo apt-get install build-essential
  - pushd /tmp && wget https://dl.google.com/go/go1.10.2.linux-amd64.tar.gz && tar -xf go1.10.2.linux-amd64.tar.gz && sudo cp -R go /usr/local/ && popd
  - mkdir -p ~/src/github.com/DavidHuie
  - ln -s `pwd` ~/src/github.com/DavidHuie/quartz
env:
  - GOROOT=/usr/local/go GOPATH=~/ PATH=$GOROOT/bin:$GOPATH/bin:$PATH
script:
  - bundle exec rake
